 
FOR /L %%A IN (1,1,1) DO ( 
	ECHO %%A this is tab number %%A 
	timeout /t 0 
	Start Chrome.exe http://www.example.net/ 
	timeout /t -20 
	Start Chrome.exe http://www.example.org/books/activity 
	timeout /t -20 
	Start Chrome.exe  http://example.com/#box 
	timeout /t -20 
	Start Chrome.exe http://www.example.edu/bells 
	timeout /t -20 
	Start Chrome.exe https://example.org/ 
	timeout /t -20 
	Start Chrome.exe http://example.com/ 
	timeout /t -20 
	Start Chrome.exe http://boat.example.com/ 
	timeout /t -20 
	Start Chrome.exe http://example.com/ 
	timeout /t -20 
	Start Chrome.exe https://www.example.edu/book#breath 
	timeout /t -20 
	Start Chrome.exe https://www.example.net/?appliance=ball&bike=basin 
	timeout /t -20 
	Start Chrome.exe http://www.example.com/base/brother.php 
	timeout /t -20 
	Start Chrome.exe https://www.example.com/#agreement 
	timeout /t -20 
	Start Chrome.exe http://example.org/book.php#board 
	timeout /t -20 
	Start Chrome.exe https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe https://example.com/ 
	timeout /t -20 
	Start Chrome.exe http://example.com/?afterthought=art&bat=brake 
	timeout /t -20 
	Start Chrome.exe  example.com/border/bone 
	timeout /t -20 
	Start Chrome.exe  http://apparel.example.com/?bikes=act 
	timeout /t -20 
	Start Chrome.exe  http://www.example.net/anger/birds 
	timeout /t -20 
	Start Chrome.exe  https://bell.example.org/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://example.com/?base=battle 
	timeout /t -20 
	Start Chrome.exe  http://example.com/?board=attack&argument=blade 
	timeout /t -20 
	Start Chrome.exe  http://www.example.net/bell/blow.htm#apparatus 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/branch/afternoon.html 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/?animal=brick&berry=bee 
	timeout /t -20 
	Start Chrome.exe  http://www.example.net/basketball.aspx 
	timeout /t -20 
	Start Chrome.exe  http://example.com/actor.aspx?bubble=bikes&basket=bird 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/border 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/#account 
	timeout /t -20 
	Start Chrome.exe  https://www.example.net/ 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/bomb.html 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/birth.php 
	timeout /t -20 
	Start Chrome.exe  http://example.com/aunt/agreement 
	timeout /t -20 
	Start Chrome.exe  http://beds.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.edu/?birds=bath&adjustment=birthday 
	timeout /t -20 
	Start Chrome.exe  https://www.example.net/boundary/birth.aspx 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/basket/arm 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.org/army.php 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/#basket 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  http://example.com/beginner.php 
	timeout /t -20 
	Start Chrome.exe  https://www.example.edu/ 
	timeout /t -20 
	Start Chrome.exe  http://www.example.net/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/aftermath/blood.htm 
	timeout /t -20 
	Start Chrome.exe  http://basket.example.org/ 
	timeout /t -20 
	Start Chrome.exe  http://border.example.com/bomb.html 
	timeout /t -20 
	Start Chrome.exe  http://boundary.example.net/bit/branch.php 
	timeout /t -20 
	Start Chrome.exe  https://basin.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/amusement/birth 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  http://example.com/?base=approval&bite=beds 
	timeout /t -20 
	Start Chrome.exe  https://boot.example.org/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.net/basketball 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/birds/bell.php 
	timeout /t -20 
	Start Chrome.exe  http://example.org/ 
	timeout /t -20 
	Start Chrome.exe  http://www.example.net/box.php 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://example.com/brass/adjustment.php 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/basket 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/acoustics.html#brick 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  http://example.com/?bone=amusement 
	timeout /t -20 
	Start Chrome.exe  https://example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://example.com/bite.html 
	timeout /t -20 
	Start Chrome.exe  https://achiever.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.net/arithmetic/birthday.php?apparel=aunt#act 
	timeout /t -20 
	Start Chrome.exe  http://example.com/bedroom#arithmetic 
	timeout /t -20 
	Start Chrome.exe  https://example.com/blood 
	timeout /t -20 
	Start Chrome.exe  http://example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/alarm.html 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.net/behavior/afternoon.aspx 
	timeout /t -20 
	Start Chrome.exe  https://example.com/bat/bell.aspx?acoustics=breath&base=breath#boundary 
	timeout /t -20 
	Start Chrome.exe  https://www.example.net/ 
	timeout /t -20 
	Start Chrome.exe  http://example.com/bikes/board?bedroom=adjustment&acoustics=blood 
	timeout /t -20 
	Start Chrome.exe  https://example.com/alarm.html 
	timeout /t -20 
	Start Chrome.exe  https://beginner.example.com/apparatus 
	timeout /t -20 
	Start Chrome.exe  http://example.net/#bird 
	timeout /t -20 
	Start Chrome.exe  https://www.example.edu/ 
	timeout /t -20 
	Start Chrome.exe  https://www.example.com/ 
	timeout /t -20 
	Start Chrome.exe  https://example.com/appliance/baseball.html 
	timeout /t -20 
	Start Chrome.exe  http://example.com/approval/box.aspx 
	timeout /t -20 
	Start Chrome.exe  http://example.org/?boat=battle&battle=bait 
	timeout /t -20 
	Start Chrome.exe  http://airplane.example.org/basketball.aspx 
	timeout /t -20 
	Start Chrome.exe  http://example.com/?bead=bomb 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/baby.htm?bells=afterthought&act=aunt 
	timeout /t -20 
	Start Chrome.exe  https://example.com/air 
	timeout /t -20 
	Start Chrome.exe  http://www.example.com/acoustics/angle 
	timeout /t -20 
	Start Chrome.exe  http://example.com/?action=birthday 
	timeout /t -20 
	Start Chrome.exe  http://www.example.org/berry 
	timeout /t -20 
	Start Chrome.exe  http://example.com/?balance=blood&birth=bear#air 
	timeout /t -20
	start Chrome.exe https://bike.example.net/?birth=book#bait 
	timeout /t -20 
	start Chrome.exe  https://www.example.com/ 

 ) 

 for /L %%B in (1,1,1) DO (  
   Echo %%B this is tab number %%B 
   timeout /t 0
   taskkill /IM Chrome.exe  
) 

 if not DEFINED IS_MINIMIZED set IS_MINIMIZED=1 && start explorer /max  

 taskkill /IM explorer 


 break 

 && exit 
 
